[tool.poetry]
name = "ATRIbot"
version = "0.1.0"
description = "ATRIbot"
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<4.0.0"
nonebot2 = "^2.0.0-beta.1"
nonebot-adapter-onebot = "^2.1.3"
requests = "^2.28.1"
nonebot-plugin-atri = "^0.0.4"
nonebot-bison = "^0.6.3"
nonebot-plugin-chatgpt = "^0.7.0"

[tool.poetry.dev-dependencies]
nb-cli = "^0.6.0"

[tool.nonebot]
plugins = ["nonebot_plugin_atri", "nonebot_bison", "nonebot_plugin_chatgpt"]
plugin_dirs = ["atribot/plugins"]

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
