[tool.poetry]
name = "ATRIbot"
version = "0.1.0"
description = "ATRIbot"
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8.3"
nonebot2 = "^2.0.0-beta.1"
nonebot-adapter-onebot = "^2.1.3"
requests = "^2.28.1"
elf-rss = "^2.6.11"
nonebot-plugin-atri = "^0.0.4"

[tool.poetry.dev-dependencies]
nb-cli = "^0.6.0"

[tool.nonebot]
plugins = ["nonebot_plugin_atri", "ELF_RSS2"]
plugin_dirs = ["atribot/plugins"]

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
